server.port: 7001
server.error.include-message: always

logging:
  level:
    root: INFO
    aw.micro: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

spring:
  cloud:
    function:
      definition: messageProcessor
    stream:
      defaultBinder: rabbit
      default:
        contentType: application/json
      bindings:
        messageProcessor-in-0:
          destination: products
          group: productsGroup
          consumer:
            maxAttempts: 3
            backOffInitialInterval: 500
            backOffMaxInterval: 1000
            backOffMultiplier: 2.0
      rabbit:
        bindings:
          messageProcessor-in-0:
            consumer:
              autoBindDlq: true
              republishToDlq: true
      kafka:
        binder:
          brokers: 127.0.0.1
          defaultBrokerPort: 9092
        bindings:
          messageProcessor-in-0:
            consumer:
              enableDlq: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-db