server:
  port: 7003
  error:
    include-message: always

# Strongly recommend to set this property to "none" in a production environment!
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost/review-db
    username: user
    password: pwd
    hikari:
      initializationFailTimeout: 60000

  cloud:
    function:
      definition: messageProcessor
    stream:
      defaultBinder: rabbit
      default:
        contentType: application/json
      bindings:
        messageProcessor-in-0:
          destination: reviews
          group: reviewsGroup
          consumer:
            maxAttempts: 3
            backOffInitialInterval: 500
            backOffMaxInterval: 1000
            backOffMultiplier: 2.0
      rabbit:
        bindings:
          messageProcessor-in-0:
            consumer:
              autoBindDlq: true
              republishToDlq: true
      kafka:
        bindings:
          messageProcessor-in-0:
            consumer:
              enableDlq: true
        binder:
          brokers: 127.0.0.1
          defaultBrokerPort: 9092

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

logging:
  level:
    root: INFO
    se.magnus: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
