server.port: 7003
server.error.include-message: always

spring.jpa.hibernate.ddl-auto: update #none in production
spring.datasource.hikari.initializationFailTimeout: 60000

spring.datasource:
  url: jdbc:mysql://localhost/review-db
  username: user
  password: pwd

logging:
  level:
    root: INFO
    aw.micro: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
